//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonzianiSwissTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PonzianiSwissTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Participants&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;Borisov, Lubomir&quot;,
        ///      &quot;FideRating&quot;: 1720,
        ///      &quot;AlternativeRating&quot;: 0,
        ///      &quot;Title&quot;: 8,
        ///      &quot;FideId&quot;: 2907801,
        ///      &quot;Federation&quot;: &quot;BUL&quot;,
        ///      &quot;ParticipantId&quot;: null,
        ///      &quot;RankId&quot;: null,
        ///      &quot;Active&quot;: null,
        ///      &quot;Rank&quot;: 0,
        ///      &quot;Club&quot;: &quot;&quot;,
        ///      &quot;YearOfBirth&quot;: 1954,
        ///      &quot;Sex&quot;: 0,
        ///      &quot;Attributes&quot;: {}
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;Duda, Antonin&quot;,
        ///      &quot;FideRating&quot;: 2038,
        ///      &quot;AlternativeRating&quot;: 0,
        ///      &quot;Title&quot;: 8,
        ///      &quot;Fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tournament_100_Participants_0_Rounds_tjson {
            get {
                return ResourceManager.GetString("Tournament_100_Participants_0_Rounds.tjson", resourceCulture);
            }
        }
    }
}
