//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonzianiSwissTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PonzianiSwissTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;Participants&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;$values&quot;: [
        ///      {
        ///        &quot;$id&quot;: &quot;3&quot;,
        ///        &quot;Name&quot;: &quot;Ramos Perez, Juan Diego&quot;,
        ///        &quot;FideRating&quot;: 1235,
        ///        &quot;AlternativeRating&quot;: 0,
        ///        &quot;Title&quot;: 8,
        ///        &quot;FideId&quot;: 54513090,
        ///        &quot;Federation&quot;: &quot;ESP&quot;,
        ///        &quot;ParticipantId&quot;: null,
        ///        &quot;RankId&quot;: null,
        ///        &quot;Active&quot;: null,
        ///        &quot;Rank&quot;: 0,
        ///        &quot;Club&quot;: &quot;&quot;,
        ///        &quot;YearOfBirth&quot;: 1978,
        ///        &quot;Sex&quot;: 0,
        ///        &quot;Attributes&quot;: {
        ///          &quot;$id&quot;: &quot;4&quot;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tournament_100_Participants_0_Rounds_tjson {
            get {
                return ResourceManager.GetString("Tournament_100_Participants_0_Rounds.tjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;Participants&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;$values&quot;: [
        ///      {
        ///        &quot;$id&quot;: &quot;3&quot;,
        ///        &quot;Name&quot;: &quot;Ivanov, Alexander&quot;,
        ///        &quot;FideRating&quot;: 2463,
        ///        &quot;AlternativeRating&quot;: 0,
        ///        &quot;Title&quot;: 0,
        ///        &quot;FideId&quot;: 2000202,
        ///        &quot;Federation&quot;: &quot;USA&quot;,
        ///        &quot;ParticipantId&quot;: &quot;1&quot;,
        ///        &quot;RankId&quot;: &quot;1&quot;,
        ///        &quot;Active&quot;: null,
        ///        &quot;Rank&quot;: 1,
        ///        &quot;Club&quot;: &quot;&quot;,
        ///        &quot;YearOfBirth&quot;: 1956,
        ///        &quot;Sex&quot;: 0,
        ///        &quot;Attributes&quot;: {
        ///          &quot;$id&quot;: &quot;4&quot;
        ///        }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tournament_100P_3R_ForbiddenPairings_json {
            get {
                return ResourceManager.GetString("Tournament_100P_3R_ForbiddenPairings.json", resourceCulture);
            }
        }
    }
}
