//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonzianiSwissTest.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PonzianiSwissTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;Participants&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;$values&quot;: [
        ///      {
        ///        &quot;$id&quot;: &quot;3&quot;,
        ///        &quot;Name&quot;: &quot;Ramos Perez, Juan Diego&quot;,
        ///        &quot;FideRating&quot;: 1235,
        ///        &quot;AlternativeRating&quot;: 0,
        ///        &quot;Title&quot;: 8,
        ///        &quot;FideId&quot;: 54513090,
        ///        &quot;Federation&quot;: &quot;ESP&quot;,
        ///        &quot;ParticipantId&quot;: null,
        ///        &quot;RankId&quot;: null,
        ///        &quot;Active&quot;: null,
        ///        &quot;Rank&quot;: 0,
        ///        &quot;Club&quot;: &quot;&quot;,
        ///        &quot;YearOfBirth&quot;: 1978,
        ///        &quot;Sex&quot;: 0,
        ///        &quot;Attributes&quot;: {
        ///          &quot;$id&quot;: &quot;4&quot;
        ///    [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string Tournament_100_Participants_0_Rounds_tjson {
            get {
                return ResourceManager.GetString("Tournament_100_Participants_0_Rounds.tjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;Participants&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;$values&quot;: [
        ///      {
        ///        &quot;$id&quot;: &quot;3&quot;,
        ///        &quot;Name&quot;: &quot;Ivanov, Alexander&quot;,
        ///        &quot;FideRating&quot;: 2463,
        ///        &quot;AlternativeRating&quot;: 0,
        ///        &quot;Title&quot;: 0,
        ///        &quot;FideId&quot;: 2000202,
        ///        &quot;Federation&quot;: &quot;USA&quot;,
        ///        &quot;ParticipantId&quot;: &quot;1&quot;,
        ///        &quot;RankId&quot;: &quot;1&quot;,
        ///        &quot;Active&quot;: null,
        ///        &quot;Rank&quot;: 1,
        ///        &quot;Club&quot;: &quot;&quot;,
        ///        &quot;YearOfBirth&quot;: 1956,
        ///        &quot;Sex&quot;: 0,
        ///        &quot;Attributes&quot;: {
        ///          &quot;$id&quot;: &quot;4&quot;
        ///        }
        ///  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string Tournament_100P_3R_ForbiddenPairings_json {
            get {
                return ResourceManager.GetString("Tournament_100P_3R_ForbiddenPairings.json", resourceCulture);
            }
        }
    }
}
