//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonzianiSwiss.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PonzianiSwiss.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find more information at https://github.com/guentherc/PonzianiSwiss ähnelt.
        /// </summary>
        public static string About_Dialog_Text {
            get {
                return ResourceManager.GetString("About_Dialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PonzianiSwiss {0} - Swiss Pairing Program ähnelt.
        /// </summary>
        public static string About_Dialog_Title {
            get {
                return ResourceManager.GetString("About_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additional Ranking ähnelt.
        /// </summary>
        public static string AdditionalRankingDialog_Title {
            get {
                return ResourceManager.GetString("AdditionalRankingDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update failed ähnelt.
        /// </summary>
        public static string Base_Update_Failed_Title {
            get {
                return ResourceManager.GetString("Base_Update_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update of {0} might take some time ähnelt.
        /// </summary>
        public static string Base_Update_Might_Take {
            get {
                return ResourceManager.GetString("Base_Update_Might_Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update successful ähnelt.
        /// </summary>
        public static string Base_Update_Ok_Title {
            get {
                return ResourceManager.GetString("Base_Update_Ok_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update of Player Base {0} ähnelt.
        /// </summary>
        public static string Base_Update_Text {
            get {
                return ResourceManager.GetString("Base_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string Button_Add_Additional_Ranking_Content {
            get {
                return ResourceManager.GetString("Button_Add_Additional_Ranking_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Additional Ranking ähnelt.
        /// </summary>
        public static string Button_Add_Additional_Ranking_ToolTip {
            get {
                return ResourceManager.GetString("Button_Add_Additional_Ranking_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additional Attributes ähnelt.
        /// </summary>
        public static string Button_AdditionalAttributes_Content {
            get {
                return ResourceManager.GetString("Button_AdditionalAttributes_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Button_Cancel_Content {
            get {
                return ResourceManager.GetString("Button_Cancel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Tiebreak ähnelt.
        /// </summary>
        public static string Button_Edit_Tiebreak_ToolTip {
            get {
                return ResourceManager.GetString("Button_Edit_Tiebreak_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search Player in National Base ähnelt.
        /// </summary>
        public static string Button_NationalBase_ToolTip {
            get {
                return ResourceManager.GetString("Button_NationalBase_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        public static string Button_Ok_Content {
            get {
                return ResourceManager.GetString("Button_Ok_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Button_Save_Content {
            get {
                return ResourceManager.GetString("Button_Save_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Baku Acceleration ähnelt.
        /// </summary>
        public static string CheckBox_Baku_Acceleration_Content {
            get {
                return ResourceManager.GetString("CheckBox_Baku_Acceleration_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Female ähnelt.
        /// </summary>
        public static string CheckBox_Female_Content {
            get {
                return ResourceManager.GetString("CheckBox_Female_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team Ranking ähnelt.
        /// </summary>
        public static string CheckBox_Team_Ranking_Content {
            get {
                return ResourceManager.GetString("CheckBox_Team_Ranking_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Performance (Elo) ähnelt.
        /// </summary>
        public static string ColHeaderEloPerformance_Content {
            get {
                return ResourceManager.GetString("ColHeaderEloPerformance_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Club ähnelt.
        /// </summary>
        public static string ColHeaderParticipantClub_Content {
            get {
                return ResourceManager.GetString("ColHeaderParticipantClub_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elo ähnelt.
        /// </summary>
        public static string ColHeaderParticipantElo_Content {
            get {
                return ResourceManager.GetString("ColHeaderParticipantElo_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Federation ähnelt.
        /// </summary>
        public static string ColHeaderParticipantFederation_Content {
            get {
                return ResourceManager.GetString("ColHeaderParticipantFederation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fide Id ähnelt.
        /// </summary>
        public static string ColHeaderParticipantFideId_Content {
            get {
                return ResourceManager.GetString("ColHeaderParticipantFideId_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Id ähnelt.
        /// </summary>
        public static string ColHeaderParticipantId_Content {
            get {
                return ResourceManager.GetString("ColHeaderParticipantId_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string ColHeaderParticipantName_Content {
            get {
                return ResourceManager.GetString("ColHeaderParticipantName_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die National Rating ähnelt.
        /// </summary>
        public static string ColHeaderParticipantNationalRating_Content {
            get {
                return ResourceManager.GetString("ColHeaderParticipantNationalRating_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rating ähnelt.
        /// </summary>
        public static string ColHeaderParticipantRating_Content {
            get {
                return ResourceManager.GetString("ColHeaderParticipantRating_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score ähnelt.
        /// </summary>
        public static string ColHeaderParticipantScore_Content {
            get {
                return ResourceManager.GetString("ColHeaderParticipantScore_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Performance (Tournament Rating) ähnelt.
        /// </summary>
        public static string ColHeaderTournamentPerformance_Content {
            get {
                return ResourceManager.GetString("ColHeaderTournamentPerformance_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crosstable ähnelt.
        /// </summary>
        public static string Crosstable {
            get {
                return ResourceManager.GetString("Crosstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There might be unsaved data which will be lost! Do you want to proceed? ähnelt.
        /// </summary>
        public static string Data_Loss_Exit_Text {
            get {
                return ResourceManager.GetString("Data_Loss_Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit Application ähnelt.
        /// </summary>
        public static string Data_Loss_Exit_Title {
            get {
                return ResourceManager.GetString("Data_Loss_Exit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There might be unsaved data which will be lost! Do you want to proceed? ähnelt.
        /// </summary>
        public static string Data_Loss_Open_Text {
            get {
                return ResourceManager.GetString("Data_Loss_Open_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Tournament ähnelt.
        /// </summary>
        public static string Data_Loss_Open_Title {
            get {
                return ResourceManager.GetString("Data_Loss_Open_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait... ähnelt.
        /// </summary>
        public static string Dialog_Title_Wait {
            get {
                return ResourceManager.GetString("Dialog_Title_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw might take some time ähnelt.
        /// </summary>
        public static string Draw_Takes_Time {
            get {
                return ResourceManager.GetString("Draw_Takes_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team Ranking ähnelt.
        /// </summary>
        public static string Export_Team_Ranking_Header {
            get {
                return ResourceManager.GetString("Export_Team_Ranking_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tournament Report|*.trf|All Files|*.* ähnelt.
        /// </summary>
        public static string Export_TRF_Dialog_Filter {
            get {
                return ResourceManager.GetString("Export_TRF_Dialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Tournament Report ähnelt.
        /// </summary>
        public static string Export_TRF_Dialog_Title {
            get {
                return ResourceManager.GetString("Export_TRF_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string ForbiddenPairingsDialog_Add {
            get {
                return ResourceManager.GetString("ForbiddenPairingsDialog_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Avoid Pairings from same Club ähnelt.
        /// </summary>
        public static string ForbiddenPairingsDialog_AvoidPairingsFromSameClub {
            get {
                return ResourceManager.GetString("ForbiddenPairingsDialog_AvoidPairingsFromSameClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Avoid Pairings from same Federation ähnelt.
        /// </summary>
        public static string ForbiddenPairingsDialog_AvoidPairingsFromSameFederation {
            get {
                return ResourceManager.GetString("ForbiddenPairingsDialog_AvoidPairingsFromSameFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define Forbidden Pairing: ähnelt.
        /// </summary>
        public static string ForbiddenPairingsDialog_DefineForbiddenPairing {
            get {
                return ResourceManager.GetString("ForbiddenPairingsDialog_DefineForbiddenPairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Federation vs Federation ähnelt.
        /// </summary>
        public static string ForbiddenPairingsDialog_FederationVsFederation {
            get {
                return ResourceManager.GetString("ForbiddenPairingsDialog_FederationVsFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List of forbidden pairings ähnelt.
        /// </summary>
        public static string ForbiddenPairingsDialog_ListOfForbiddenPairings {
            get {
                return ResourceManager.GetString("ForbiddenPairingsDialog_ListOfForbiddenPairings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player 1 ähnelt.
        /// </summary>
        public static string ForbiddenPairingsDialog_Player1 {
            get {
                return ResourceManager.GetString("ForbiddenPairingsDialog_Player1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player 2 ähnelt.
        /// </summary>
        public static string ForbiddenPairingsDialog_Player2 {
            get {
                return ResourceManager.GetString("ForbiddenPairingsDialog_Player2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player vs Federation ähnelt.
        /// </summary>
        public static string ForbiddenPairingsDialog_PlayerVsFederation {
            get {
                return ResourceManager.GetString("ForbiddenPairingsDialog_PlayerVsFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player vs Player ähnelt.
        /// </summary>
        public static string ForbiddenPairingsDialog_PlayerVsPlayer {
            get {
                return ResourceManager.GetString("ForbiddenPairingsDialog_PlayerVsPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special Options ähnelt.
        /// </summary>
        public static string ForbiddenPairingsDialog_SpecialOptions {
            get {
                return ResourceManager.GetString("ForbiddenPairingsDialog_SpecialOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard Options ähnelt.
        /// </summary>
        public static string ForbiddenPairingsDialog_StandardOptions {
            get {
                return ResourceManager.GetString("ForbiddenPairingsDialog_StandardOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forbidden Pairings ähnelt.
        /// </summary>
        public static string ForbiddenPairingsDialog_Title {
            get {
                return ResourceManager.GetString("ForbiddenPairingsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected Tiebreak Rules ähnelt.
        /// </summary>
        public static string GridViewColumnHeader_Selected_Content {
            get {
                return ResourceManager.GetString("GridViewColumnHeader_Selected_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoring Scheme ähnelt.
        /// </summary>
        public static string GroupBox_ScoringScheme_Header {
            get {
                return ResourceManager.GetString("GroupBox_ScoringScheme_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sex ähnelt.
        /// </summary>
        public static string Label_AdditionalRanking_Sex_Content {
            get {
                return ResourceManager.GetString("Label_AdditionalRanking_Sex_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Label_AdditionalRanking_Title_Content {
            get {
                return ResourceManager.GetString("Label_AdditionalRanking_Title_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birth Year from ähnelt.
        /// </summary>
        public static string Label_BirthYear_From_Content {
            get {
                return ResourceManager.GetString("Label_BirthYear_From_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die to ähnelt.
        /// </summary>
        public static string Label_BirthYear_To {
            get {
                return ResourceManager.GetString("Label_BirthYear_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rating from ähnelt.
        /// </summary>
        public static string Label_Rating_From_Content {
            get {
                return ResourceManager.GetString("Label_Rating_From_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die to ähnelt.
        /// </summary>
        public static string Label_Rating_To_Content {
            get {
                return ResourceManager.GetString("Label_Rating_To_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team Size: ähnelt.
        /// </summary>
        public static string Label_Team_Size_Content {
            get {
                return ResourceManager.GetString("Label_Team_Size_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Tournament {0} ähnelt.
        /// </summary>
        public static string Load_Tournament_Message_Title {
            get {
                return ResourceManager.GetString("Load_Tournament_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additional Rankings ähnelt.
        /// </summary>
        public static string MenuItem_Additional_Rankings_Export_Header {
            get {
                return ResourceManager.GetString("MenuItem_Additional_Rankings_Export_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string MenuItem_AdditionalRanking_Add_Header {
            get {
                return ResourceManager.GetString("MenuItem_AdditionalRanking_Add_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string MenuItem_AdditionalRanking_Delete_Header {
            get {
                return ResourceManager.GetString("MenuItem_AdditionalRanking_Delete_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string MenuItem_AdditionalRanking_Edit_Header {
            get {
                return ResourceManager.GetString("MenuItem_AdditionalRanking_Edit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bye ähnelt.
        /// </summary>
        public static string MenuItem_Bye_Header {
            get {
                return ResourceManager.GetString("MenuItem_Bye_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forfeit ähnelt.
        /// </summary>
        public static string MenuItem_Forfeit_Header {
            get {
                return ResourceManager.GetString("MenuItem_Forfeit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abandon Tournament ähnelt.
        /// </summary>
        public static string MenuItem_Participant_Abandon_Header {
            get {
                return ResourceManager.GetString("MenuItem_Participant_Abandon_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string MenuItem_Participant_Delete_Header {
            get {
                return ResourceManager.GetString("MenuItem_Participant_Delete_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string MenuItem_Participant_Edit_Header {
            get {
                return ResourceManager.GetString("MenuItem_Participant_Edit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause Next Round ähnelt.
        /// </summary>
        public static string MenuItem_Participant_Pause_Header {
            get {
                return ResourceManager.GetString("MenuItem_Participant_Pause_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo Abandon/Pause ähnelt.
        /// </summary>
        public static string MenuItem_Participant_Undo_Pause_Header {
            get {
                return ResourceManager.GetString("MenuItem_Participant_Undo_Pause_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string MenuItem_Participants_Add_Header {
            get {
                return ResourceManager.GetString("MenuItem_Participants_Add_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Participants ähnelt.
        /// </summary>
        public static string MenuItem_Participants_Header {
            get {
                return ResourceManager.GetString("MenuItem_Participants_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player Base ähnelt.
        /// </summary>
        public static string MenuItem_PlayerBase_Header {
            get {
                return ResourceManager.GetString("MenuItem_PlayerBase_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        public static string MenuItem_PlayerBase_Update_Header {
            get {
                return ResourceManager.GetString("MenuItem_PlayerBase_Update_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent Files ähnelt.
        /// </summary>
        public static string MenuItem_Recent_Files_Header {
            get {
                return ResourceManager.GetString("MenuItem_Recent_Files_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Last Round ähnelt.
        /// </summary>
        public static string MenuItem_Round_Delete_Header {
            get {
                return ResourceManager.GetString("MenuItem_Round_Delete_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw ähnelt.
        /// </summary>
        public static string MenuItem_Round_Draw_Header {
            get {
                return ResourceManager.GetString("MenuItem_Round_Draw_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Round ähnelt.
        /// </summary>
        public static string MenuItem_Round_Header {
            get {
                return ResourceManager.GetString("MenuItem_Round_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die * (Open) ähnelt.
        /// </summary>
        public static string MenuItem_Set_Result_0_Header {
            get {
                return ResourceManager.GetString("MenuItem_Set_Result_0_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string MenuItem_Settings_About_Header {
            get {
                return ResourceManager.GetString("MenuItem_Settings_About_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base Theme ähnelt.
        /// </summary>
        public static string MenuItem_Settings_Basetheme_Header {
            get {
                return ResourceManager.GetString("MenuItem_Settings_Basetheme_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string MenuItem_Settings_Header {
            get {
                return ResourceManager.GetString("MenuItem_Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string MenuItem_Settings_Language_Header {
            get {
                return ResourceManager.GetString("MenuItem_Settings_Language_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset Settings ähnelt.
        /// </summary>
        public static string MenuItem_Settings_Reset_Header {
            get {
                return ResourceManager.GetString("MenuItem_Settings_Reset_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme Color ähnelt.
        /// </summary>
        public static string MenuItem_Settings_Themecolor_Header {
            get {
                return ResourceManager.GetString("MenuItem_Settings_Themecolor_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crosstable ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_Crosstable_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_Crosstable_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Forbidden Pairings ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_Edit_Forbidden_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_Edit_Forbidden_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_Edit_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_Edit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_Exit_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_Exit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_Export_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_Export_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tournament ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_New_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_New_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ... ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_Open_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_Open_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pairings ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_Pairings_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_Pairings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Participant List ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_Participant_List_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_Participant_List_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By Name ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_Participant_List_Name_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_Participant_List_Name_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By Starting Rank ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_Participant_List_Rank_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_Participant_List_Rank_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save As ... ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_Save_As_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_Save_As_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_Save_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_Save_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TRF (Tournament Report File) ähnelt.
        /// </summary>
        public static string MenuItem_Tournament_TRF_Header {
            get {
                return ResourceManager.GetString("MenuItem_Tournament_TRF_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unrated ähnelt.
        /// </summary>
        public static string MenuItem_Unrated_Header {
            get {
                return ResourceManager.GetString("MenuItem_Unrated_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string MessageDialog_Title_Error {
            get {
                return ResourceManager.GetString("MessageDialog_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;New Additional Ranking&gt; ähnelt.
        /// </summary>
        public static string New_Additional_Ranking_Placeholder {
            get {
                return ResourceManager.GetString("New_Additional_Ranking_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Additional Rankings Created ähnelt.
        /// </summary>
        public static string No_Additional_Rankings {
            get {
                return ResourceManager.GetString("No_Additional_Rankings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tournament Files|*.tjson|All Files|*.* ähnelt.
        /// </summary>
        public static string Open_Tournament_Dialog_Filter {
            get {
                return ResourceManager.GetString("Open_Tournament_Dialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Tournament ähnelt.
        /// </summary>
        public static string Open_Tournament_Dialog_Title {
            get {
                return ResourceManager.GetString("Open_Tournament_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pairings Round {0} ähnelt.
        /// </summary>
        public static string Pairings_Round_X {
            get {
                return ResourceManager.GetString("Pairings_Round_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Participant List by Name ähnelt.
        /// </summary>
        public static string Participant_List_by_Name {
            get {
                return ResourceManager.GetString("Participant_List_by_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Participant List by Starting Rank ähnelt.
        /// </summary>
        public static string Participant_List_by_Starting_Rank {
            get {
                return ResourceManager.GetString("Participant_List_by_Starting_Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string ParticipantAttributeDialog_Column_Name_Header {
            get {
                return ResourceManager.GetString("ParticipantAttributeDialog_Column_Name_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        public static string ParticipantAttributeDialog_Column_Value_Header {
            get {
                return ResourceManager.GetString("ParticipantAttributeDialog_Column_Value_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicate Key ähnelt.
        /// </summary>
        public static string ParticipantAttributeDialog_DuplicateMessage_Caption {
            get {
                return ResourceManager.GetString("ParticipantAttributeDialog_DuplicateMessage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicate Attribute Key: {0} - Keys must be unique! ähnelt.
        /// </summary>
        public static string ParticipantAttributeDialog_DuplicateMessage_Text {
            get {
                return ResourceManager.GetString("ParticipantAttributeDialog_DuplicateMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Participant Attributes ähnelt.
        /// </summary>
        public static string ParticipantAttributeDialog_Title {
            get {
                return ResourceManager.GetString("ParticipantAttributeDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alternative Rating: ähnelt.
        /// </summary>
        public static string ParticipantDialog_Label_AltRating_Content {
            get {
                return ResourceManager.GetString("ParticipantDialog_Label_AltRating_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Club: ähnelt.
        /// </summary>
        public static string ParticipantDialog_Label_Club_Content {
            get {
                return ResourceManager.GetString("ParticipantDialog_Label_Club_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Federation: ähnelt.
        /// </summary>
        public static string ParticipantDialog_Label_Federation_Content {
            get {
                return ResourceManager.GetString("ParticipantDialog_Label_Federation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fide ID: ähnelt.
        /// </summary>
        public static string ParticipantDialog_Label_FideID_Content {
            get {
                return ResourceManager.GetString("ParticipantDialog_Label_FideID_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string ParticipantDialog_Label_Name_Content {
            get {
                return ResourceManager.GetString("ParticipantDialog_Label_Name_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rating: ähnelt.
        /// </summary>
        public static string ParticipantDialog_Label_Rating_Content {
            get {
                return ResourceManager.GetString("ParticipantDialog_Label_Rating_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title: ähnelt.
        /// </summary>
        public static string ParticipantDialog_Label_Title_Content {
            get {
                return ResourceManager.GetString("ParticipantDialog_Label_Title_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year of Birth: ähnelt.
        /// </summary>
        public static string ParticipantDialog_Label_YearOfBirth_Content {
            get {
                return ResourceManager.GetString("ParticipantDialog_Label_YearOfBirth_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Participant ähnelt.
        /// </summary>
        public static string ParticipantDialog_Title {
            get {
                return ResourceManager.GetString("ParticipantDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Female ähnelt.
        /// </summary>
        public static string PlayerSearchDialog_Checkbox_Female_Content {
            get {
                return ResourceManager.GetString("PlayerSearchDialog_Checkbox_Female_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        public static string PlayerSearchDialog_Groupbox_Data_Header {
            get {
                return ResourceManager.GetString("PlayerSearchDialog_Groupbox_Data_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Club: ähnelt.
        /// </summary>
        public static string PlayerSearchDialog_Label_Club_Content {
            get {
                return ResourceManager.GetString("PlayerSearchDialog_Label_Club_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Source: ähnelt.
        /// </summary>
        public static string PlayerSearchDialog_Label_DataSource_Content {
            get {
                return ResourceManager.GetString("PlayerSearchDialog_Label_DataSource_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Federation: ähnelt.
        /// </summary>
        public static string PlayerSearchDialog_Label_Federation_Content {
            get {
                return ResourceManager.GetString("PlayerSearchDialog_Label_Federation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Id: ähnelt.
        /// </summary>
        public static string PlayerSearchDialog_Label_Id_Content {
            get {
                return ResourceManager.GetString("PlayerSearchDialog_Label_Id_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string PlayerSearchDialog_Label_Name_Content {
            get {
                return ResourceManager.GetString("PlayerSearchDialog_Label_Name_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die National Rating: ähnelt.
        /// </summary>
        public static string PlayerSearchDialog_Label_NationalRating_Content {
            get {
                return ResourceManager.GetString("PlayerSearchDialog_Label_NationalRating_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year of Birth: ähnelt.
        /// </summary>
        public static string PlayerSearchDialog_Label_YearOfBirth_Content {
            get {
                return ResourceManager.GetString("PlayerSearchDialog_Label_YearOfBirth_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Black ähnelt.
        /// </summary>
        public static string Round_Column_Header_Black {
            get {
                return ResourceManager.GetString("Round_Column_Header_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Id ähnelt.
        /// </summary>
        public static string Round_Column_Header_Id_Black {
            get {
                return ResourceManager.GetString("Round_Column_Header_Id_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Id ähnelt.
        /// </summary>
        public static string Round_Column_Header_Id_White {
            get {
                return ResourceManager.GetString("Round_Column_Header_Id_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        public static string Round_Column_Header_Result {
            get {
                return ResourceManager.GetString("Round_Column_Header_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die White ähnelt.
        /// </summary>
        public static string Round_Column_Header_White {
            get {
                return ResourceManager.GetString("Round_Column_Header_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Tournament ähnelt.
        /// </summary>
        public static string Save_Tournament_Dialog_Title {
            get {
                return ResourceManager.GetString("Save_Tournament_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        public static string SexExtended_All {
            get {
                return ResourceManager.GetString("SexExtended_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Female ähnelt.
        /// </summary>
        public static string SexExtended_Female {
            get {
                return ResourceManager.GetString("SexExtended_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Male ähnelt.
        /// </summary>
        public static string SexExtended_Male {
            get {
                return ResourceManager.GetString("SexExtended_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additional Rankings ähnelt.
        /// </summary>
        public static string TabItem_AdditionalRankings_Header {
            get {
                return ResourceManager.GetString("TabItem_AdditionalRankings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Participants ähnelt.
        /// </summary>
        public static string TabItem_Participants_Header {
            get {
                return ResourceManager.GetString("TabItem_Participants_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Down ähnelt.
        /// </summary>
        public static string TiebreakDialog_MenuItem_MoveDown_Header {
            get {
                return ResourceManager.GetString("TiebreakDialog_MenuItem_MoveDown_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Up ähnelt.
        /// </summary>
        public static string TiebreakDialog_MenuItem_MoveUp_Header {
            get {
                return ResourceManager.GetString("TiebreakDialog_MenuItem_MoveUp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Tiebreak Rules ähnelt.
        /// </summary>
        public static string TiebreakDialog_Title {
            get {
                return ResourceManager.GetString("TiebreakDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Player ähnelt.
        /// </summary>
        public static string Toolbar_Participant_Add {
            get {
                return ResourceManager.GetString("Toolbar_Participant_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw Next Round ähnelt.
        /// </summary>
        public static string Toolbar_Round_Draw_ToolTip {
            get {
                return ResourceManager.GetString("Toolbar_Round_Draw_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Tournament ähnelt.
        /// </summary>
        public static string Toolbar_Tournament_Edit_ToolTip {
            get {
                return ResourceManager.GetString("Toolbar_Tournament_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create New Tournament ähnelt.
        /// </summary>
        public static string Toolbar_Tournament_New_ToolTip {
            get {
                return ResourceManager.GetString("Toolbar_Tournament_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Tournament ähnelt.
        /// </summary>
        public static string Toolbar_Tournament_Open_ToolTip {
            get {
                return ResourceManager.GetString("Toolbar_Tournament_Open_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Tournament ähnelt.
        /// </summary>
        public static string Toolbar_Tournament_Save_ToolTip {
            get {
                return ResourceManager.GetString("Toolbar_Tournament_Save_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chief Arbiter: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_ChiefArbiter_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_ChiefArbiter_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die City: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_City_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_City_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_Date_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_Date_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arbiters: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_DeputyArbiter_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_DeputyArbiter_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Federation: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_Federation_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_Federation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_Name_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_Name_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pairing System: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_PairingSystem_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_PairingSystem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Points for Draw: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_PointsForDraw_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_PointsForDraw_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Points for Forfeited Loss: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_PointsForForfeitedLoss_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_PointsForForfeitedLoss_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Points for Pairing Allocated Bye: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_PointsForPairingAllocatedBye_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_PointsForPairingAllocatedBye_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Points for Loss: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_PointsForPlayedLoss_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_PointsForPlayedLoss_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Points for Win: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_PointsForWin_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_PointsForWin_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Points for Zero Point Bye: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_PointsForZeroPointBye_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_PointsForZeroPointBye_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rating Determination: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_RatingDetermination_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_RatingDetermination_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rounds: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_Rounds_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_Rounds_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tiebreak: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_Tiebreak_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_Tiebreak_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Control: ähnelt.
        /// </summary>
        public static string TournamentDialog_Label_TimeControl_Content {
            get {
                return ResourceManager.GetString("TournamentDialog_Label_TimeControl_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tournament ähnelt.
        /// </summary>
        public static string TournamentDialogWindow_Title {
            get {
                return ResourceManager.GetString("TournamentDialogWindow_Title", resourceCulture);
            }
        }
    }
}
