//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonzianiSwissLib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PonzianiSwissLib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [{&quot;category&quot;:&quot;Member federations&quot;,&quot;continent&quot;:&quot;Africa&quot;,&quot;details_code&quot;:&quot;780&quot;,&quot;fed_short_name&quot;:&quot;ALG&quot;,&quot;fed_long_name&quot;:&quot;Algeria&quot;,&quot;fed_notice&quot;:&quot;&quot;,&quot;membership_type&quot;:&quot;1&quot;,&quot;continent_id&quot;:&quot;4&quot;,&quot;details_type&quot;:&quot;1&quot;},{&quot;category&quot;:&quot;Member federations&quot;,&quot;continent&quot;:&quot;Africa&quot;,&quot;details_code&quot;:&quot;782&quot;,&quot;fed_short_name&quot;:&quot;ANG&quot;,&quot;fed_long_name&quot;:&quot;Angola&quot;,&quot;fed_notice&quot;:&quot;&quot;,&quot;membership_type&quot;:&quot;1&quot;,&quot;continent_id&quot;:&quot;4&quot;,&quot;details_type&quot;:&quot;1&quot;},{&quot;category&quot;:&quot;Member federations&quot;,&quot;continent&quot;:&quot;Africa&quot;,&quot;details_code&quot;:&quot;806&quot;,&quot;fed_short_name&quot;:&quot;BOT&quot;,&quot;fed_long_na [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string federation_json {
            get {
                return ResourceManager.GetString("federation.json", resourceCulture);
            }
        }
    }
}
