//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonzianiSwissLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PonzianiSwissLib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;category&quot;:&quot;Member federations&quot;,&quot;continent&quot;:&quot;Africa&quot;,&quot;details_code&quot;:&quot;780&quot;,&quot;fed_short_name&quot;:&quot;ALG&quot;,&quot;fed_long_name&quot;:&quot;Algeria&quot;,&quot;fed_notice&quot;:&quot;&quot;,&quot;membership_type&quot;:&quot;1&quot;,&quot;continent_id&quot;:&quot;4&quot;,&quot;details_type&quot;:&quot;1&quot;},{&quot;category&quot;:&quot;Member federations&quot;,&quot;continent&quot;:&quot;Africa&quot;,&quot;details_code&quot;:&quot;782&quot;,&quot;fed_short_name&quot;:&quot;ANG&quot;,&quot;fed_long_name&quot;:&quot;Angola&quot;,&quot;fed_notice&quot;:&quot;&quot;,&quot;membership_type&quot;:&quot;1&quot;,&quot;continent_id&quot;:&quot;4&quot;,&quot;details_type&quot;:&quot;1&quot;},{&quot;category&quot;:&quot;Member federations&quot;,&quot;continent&quot;:&quot;Africa&quot;,&quot;details_code&quot;:&quot;806&quot;,&quot;fed_short_name&quot;:&quot;BOT&quot;,&quot;fed_long_na [rest of string was truncated]&quot;;.
        /// </summary>
        public static string federation_json {
            get {
                return ResourceManager.GetString("federation.json", resourceCulture);
            }
        }
    }
}
