//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonzianiSwissGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Federations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Federations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PonzianiSwissGui.Properties.Federations", typeof(Federations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian Chess Federation.
        /// </summary>
        internal static string ACF {
            get {
                return ResourceManager.GetString("ACF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan.
        /// </summary>
        internal static string AFG {
            get {
                return ResourceManager.GetString("AFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands Antilles.
        /// </summary>
        internal static string AHO {
            get {
                return ResourceManager.GetString("AHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania.
        /// </summary>
        internal static string ALB {
            get {
                return ResourceManager.GetString("ALB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algeria.
        /// </summary>
        internal static string ALG {
            get {
                return ResourceManager.GetString("ALG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorra.
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angola.
        /// </summary>
        internal static string ANG {
            get {
                return ResourceManager.GetString("ANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antigua and Barbuda.
        /// </summary>
        internal static string ANT {
            get {
                return ResourceManager.GetString("ANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentine.
        /// </summary>
        internal static string ARG {
            get {
                return ResourceManager.GetString("ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenia.
        /// </summary>
        internal static string ARM {
            get {
                return ResourceManager.GetString("ARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aruba.
        /// </summary>
        internal static string ARU {
            get {
                return ResourceManager.GetString("ARU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        internal static string AUS {
            get {
                return ResourceManager.GetString("AUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        internal static string AUT {
            get {
                return ResourceManager.GetString("AUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan.
        /// </summary>
        internal static string AZE {
            get {
                return ResourceManager.GetString("AZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahamas.
        /// </summary>
        internal static string BAH {
            get {
                return ResourceManager.GetString("BAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladesh.
        /// </summary>
        internal static string BAN {
            get {
                return ResourceManager.GetString("BAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbados.
        /// </summary>
        internal static string BAR {
            get {
                return ResourceManager.GetString("BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burundi.
        /// </summary>
        internal static string BDI {
            get {
                return ResourceManager.GetString("BDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        internal static string BEL {
            get {
                return ResourceManager.GetString("BEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benin.
        /// </summary>
        internal static string BEN {
            get {
                return ResourceManager.GetString("BEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhutan.
        /// </summary>
        internal static string BHU {
            get {
                return ResourceManager.GetString("BHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnia &amp; Herzegovina.
        /// </summary>
        internal static string BIH {
            get {
                return ResourceManager.GetString("BIH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarus.
        /// </summary>
        internal static string BLR {
            get {
                return ResourceManager.GetString("BLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivia.
        /// </summary>
        internal static string BOL {
            get {
                return ResourceManager.GetString("BOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botswana.
        /// </summary>
        internal static string BOT {
            get {
                return ResourceManager.GetString("BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        internal static string BRA {
            get {
                return ResourceManager.GetString("BRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahrain.
        /// </summary>
        internal static string BRN {
            get {
                return ResourceManager.GetString("BRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brunei Darussalam.
        /// </summary>
        internal static string BRU {
            get {
                return ResourceManager.GetString("BRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        internal static string BUL {
            get {
                return ResourceManager.GetString("BUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burkina Faso.
        /// </summary>
        internal static string BUR {
            get {
                return ResourceManager.GetString("BUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodia.
        /// </summary>
        internal static string CAM {
            get {
                return ResourceManager.GetString("CAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        internal static string CAN {
            get {
                return ResourceManager.GetString("CAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalonia.
        /// </summary>
        internal static string CAT {
            get {
                return ResourceManager.GetString("CAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confederation of Chess for Americas.
        /// </summary>
        internal static string CCA {
            get {
                return ResourceManager.GetString("CCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chile.
        /// </summary>
        internal static string CHI {
            get {
                return ResourceManager.GetString("CHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        internal static string CHN {
            get {
                return ResourceManager.GetString("CHN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivory Coast.
        /// </summary>
        internal static string CIV {
            get {
                return ResourceManager.GetString("CIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameroon.
        /// </summary>
        internal static string CMR {
            get {
                return ResourceManager.GetString("CMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia.
        /// </summary>
        internal static string COL {
            get {
                return ResourceManager.GetString("COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cape Verde.
        /// </summary>
        internal static string CPV {
            get {
                return ResourceManager.GetString("CPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rica.
        /// </summary>
        internal static string CRC {
            get {
                return ResourceManager.GetString("CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatia.
        /// </summary>
        internal static string CRO {
            get {
                return ResourceManager.GetString("CRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuba.
        /// </summary>
        internal static string CUB {
            get {
                return ResourceManager.GetString("CUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyprus.
        /// </summary>
        internal static string CYP {
            get {
                return ResourceManager.GetString("CYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic.
        /// </summary>
        internal static string CZE {
            get {
                return ResourceManager.GetString("CZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        internal static string DEN {
            get {
                return ResourceManager.GetString("DEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djibouti.
        /// </summary>
        internal static string DJI {
            get {
                return ResourceManager.GetString("DJI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominican Republic.
        /// </summary>
        internal static string DOM {
            get {
                return ResourceManager.GetString("DOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecuador.
        /// </summary>
        internal static string ECU {
            get {
                return ResourceManager.GetString("ECU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egypt.
        /// </summary>
        internal static string EGY {
            get {
                return ResourceManager.GetString("EGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to England.
        /// </summary>
        internal static string ENG {
            get {
                return ResourceManager.GetString("ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Salvador.
        /// </summary>
        internal static string ESA {
            get {
                return ResourceManager.GetString("ESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        internal static string ESP {
            get {
                return ResourceManager.GetString("ESP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonia.
        /// </summary>
        internal static string EST {
            get {
                return ResourceManager.GetString("EST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopia.
        /// </summary>
        internal static string ETH {
            get {
                return ResourceManager.GetString("ETH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faroe Islands.
        /// </summary>
        internal static string FAI {
            get {
                return ResourceManager.GetString("FAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIDE.
        /// </summary>
        internal static string FID {
            get {
                return ResourceManager.GetString("FID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiji.
        /// </summary>
        internal static string FIJ {
            get {
                return ResourceManager.GetString("FIJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland.
        /// </summary>
        internal static string FIN {
            get {
                return ResourceManager.GetString("FIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        internal static string FRA {
            get {
                return ResourceManager.GetString("FRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambia.
        /// </summary>
        internal static string GAM {
            get {
                return ResourceManager.GetString("GAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guernsey.
        /// </summary>
        internal static string GCI {
            get {
                return ResourceManager.GetString("GCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgia.
        /// </summary>
        internal static string GEO {
            get {
                return ResourceManager.GetString("GEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        internal static string GER {
            get {
                return ResourceManager.GetString("GER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghana.
        /// </summary>
        internal static string GHA {
            get {
                return ResourceManager.GetString("GHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece.
        /// </summary>
        internal static string GRE {
            get {
                return ResourceManager.GetString("GRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala.
        /// </summary>
        internal static string GUA {
            get {
                return ResourceManager.GetString("GUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guam.
        /// </summary>
        internal static string GUM {
            get {
                return ResourceManager.GetString("GUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haiti.
        /// </summary>
        internal static string HAI {
            get {
                return ResourceManager.GetString("HAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong.
        /// </summary>
        internal static string HKG {
            get {
                return ResourceManager.GetString("HKG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduras.
        /// </summary>
        internal static string HON {
            get {
                return ResourceManager.GetString("HON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary.
        /// </summary>
        internal static string HUN {
            get {
                return ResourceManager.GetString("HUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isle of Man.
        /// </summary>
        internal static string IMN {
            get {
                return ResourceManager.GetString("IMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesia.
        /// </summary>
        internal static string INA {
            get {
                return ResourceManager.GetString("INA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India.
        /// </summary>
        internal static string IND {
            get {
                return ResourceManager.GetString("IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran.
        /// </summary>
        internal static string IRI {
            get {
                return ResourceManager.GetString("IRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland.
        /// </summary>
        internal static string IRL {
            get {
                return ResourceManager.GetString("IRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iraq.
        /// </summary>
        internal static string IRQ {
            get {
                return ResourceManager.GetString("IRQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland.
        /// </summary>
        internal static string ISL {
            get {
                return ResourceManager.GetString("ISL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel.
        /// </summary>
        internal static string ISR {
            get {
                return ResourceManager.GetString("ISR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Virgin Islands.
        /// </summary>
        internal static string ISV {
            get {
                return ResourceManager.GetString("ISV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        internal static string ITA {
            get {
                return ResourceManager.GetString("ITA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Virgin Islands.
        /// </summary>
        internal static string IVB {
            get {
                return ResourceManager.GetString("IVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaica.
        /// </summary>
        internal static string JAM {
            get {
                return ResourceManager.GetString("JAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jersey.
        /// </summary>
        internal static string JCI {
            get {
                return ResourceManager.GetString("JCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordan.
        /// </summary>
        internal static string JOR {
            get {
                return ResourceManager.GetString("JOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        internal static string JPN {
            get {
                return ResourceManager.GetString("JPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakhstan.
        /// </summary>
        internal static string KAZ {
            get {
                return ResourceManager.GetString("KAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenya.
        /// </summary>
        internal static string KEN {
            get {
                return ResourceManager.GetString("KEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyzstan.
        /// </summary>
        internal static string KGZ {
            get {
                return ResourceManager.GetString("KGZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Korea.
        /// </summary>
        internal static string KOR {
            get {
                return ResourceManager.GetString("KOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosovo.
        /// </summary>
        internal static string KOS {
            get {
                return ResourceManager.GetString("KOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Arabia.
        /// </summary>
        internal static string KSA {
            get {
                return ResourceManager.GetString("KSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwait.
        /// </summary>
        internal static string KUW {
            get {
                return ResourceManager.GetString("KUW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laos.
        /// </summary>
        internal static string LAO {
            get {
                return ResourceManager.GetString("LAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvia.
        /// </summary>
        internal static string LAT {
            get {
                return ResourceManager.GetString("LAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libya.
        /// </summary>
        internal static string LBA {
            get {
                return ResourceManager.GetString("LBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanon.
        /// </summary>
        internal static string LBN {
            get {
                return ResourceManager.GetString("LBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberia.
        /// </summary>
        internal static string LBR {
            get {
                return ResourceManager.GetString("LBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Lucia.
        /// </summary>
        internal static string LCA {
            get {
                return ResourceManager.GetString("LCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesotho.
        /// </summary>
        internal static string LES {
            get {
                return ResourceManager.GetString("LES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtenstein.
        /// </summary>
        internal static string LIE {
            get {
                return ResourceManager.GetString("LIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuania.
        /// </summary>
        internal static string LTU {
            get {
                return ResourceManager.GetString("LTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        internal static string LUX {
            get {
                return ResourceManager.GetString("LUX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macau.
        /// </summary>
        internal static string MAC {
            get {
                return ResourceManager.GetString("MAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madagascar.
        /// </summary>
        internal static string MAD {
            get {
                return ResourceManager.GetString("MAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morocco.
        /// </summary>
        internal static string MAR {
            get {
                return ResourceManager.GetString("MAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysia.
        /// </summary>
        internal static string MAS {
            get {
                return ResourceManager.GetString("MAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malawi.
        /// </summary>
        internal static string MAW {
            get {
                return ResourceManager.GetString("MAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldova.
        /// </summary>
        internal static string MDA {
            get {
                return ResourceManager.GetString("MDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maldives.
        /// </summary>
        internal static string MDV {
            get {
                return ResourceManager.GetString("MDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        internal static string MEX {
            get {
                return ResourceManager.GetString("MEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolia.
        /// </summary>
        internal static string MGL {
            get {
                return ResourceManager.GetString("MGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Macedonia.
        /// </summary>
        internal static string MKD {
            get {
                return ResourceManager.GetString("MKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mali.
        /// </summary>
        internal static string MLI {
            get {
                return ResourceManager.GetString("MLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malta.
        /// </summary>
        internal static string MLT {
            get {
                return ResourceManager.GetString("MLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco.
        /// </summary>
        internal static string MNC {
            get {
                return ResourceManager.GetString("MNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro.
        /// </summary>
        internal static string MNE {
            get {
                return ResourceManager.GetString("MNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozambique.
        /// </summary>
        internal static string MOZ {
            get {
                return ResourceManager.GetString("MOZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritius.
        /// </summary>
        internal static string MRI {
            get {
                return ResourceManager.GetString("MRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritania.
        /// </summary>
        internal static string MTN {
            get {
                return ResourceManager.GetString("MTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar.
        /// </summary>
        internal static string MYA {
            get {
                return ResourceManager.GetString("MYA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namibia.
        /// </summary>
        internal static string NAM {
            get {
                return ResourceManager.GetString("NAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaragua.
        /// </summary>
        internal static string NCA {
            get {
                return ResourceManager.GetString("NCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        internal static string NED {
            get {
                return ResourceManager.GetString("NED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepal.
        /// </summary>
        internal static string NEP {
            get {
                return ResourceManager.GetString("NEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigeria.
        /// </summary>
        internal static string NGR {
            get {
                return ResourceManager.GetString("NGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        internal static string NOR {
            get {
                return ResourceManager.GetString("NOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand.
        /// </summary>
        internal static string NZL {
            get {
                return ResourceManager.GetString("NZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oman.
        /// </summary>
        internal static string OMA {
            get {
                return ResourceManager.GetString("OMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistan.
        /// </summary>
        internal static string PAK {
            get {
                return ResourceManager.GetString("PAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panama.
        /// </summary>
        internal static string PAN {
            get {
                return ResourceManager.GetString("PAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguay.
        /// </summary>
        internal static string PAR {
            get {
                return ResourceManager.GetString("PAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        internal static string PER {
            get {
                return ResourceManager.GetString("PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippines.
        /// </summary>
        internal static string PHI {
            get {
                return ResourceManager.GetString("PHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palestine.
        /// </summary>
        internal static string PLE {
            get {
                return ResourceManager.GetString("PLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palau.
        /// </summary>
        internal static string PLW {
            get {
                return ResourceManager.GetString("PLW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        internal static string POL {
            get {
                return ResourceManager.GetString("POL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        internal static string POR {
            get {
                return ResourceManager.GetString("POR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Rico.
        /// </summary>
        internal static string PUR {
            get {
                return ResourceManager.GetString("PUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qatar.
        /// </summary>
        internal static string QAT {
            get {
                return ResourceManager.GetString("QAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romania.
        /// </summary>
        internal static string ROU {
            get {
                return ResourceManager.GetString("ROU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa.
        /// </summary>
        internal static string RSA {
            get {
                return ResourceManager.GetString("RSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        internal static string RUS {
            get {
                return ResourceManager.GetString("RUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rwanda.
        /// </summary>
        internal static string RWA {
            get {
                return ResourceManager.GetString("RWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yugoslavia.
        /// </summary>
        internal static string SCG {
            get {
                return ResourceManager.GetString("SCG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scotland.
        /// </summary>
        internal static string SCO {
            get {
                return ResourceManager.GetString("SCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senegal.
        /// </summary>
        internal static string SEN {
            get {
                return ResourceManager.GetString("SEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seychelles.
        /// </summary>
        internal static string SEY {
            get {
                return ResourceManager.GetString("SEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore.
        /// </summary>
        internal static string SGP {
            get {
                return ResourceManager.GetString("SGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sierra Leone.
        /// </summary>
        internal static string SLE {
            get {
                return ResourceManager.GetString("SLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenia.
        /// </summary>
        internal static string SLO {
            get {
                return ResourceManager.GetString("SLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Marino.
        /// </summary>
        internal static string SMR {
            get {
                return ResourceManager.GetString("SMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solomon Islands.
        /// </summary>
        internal static string SOL {
            get {
                return ResourceManager.GetString("SOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia.
        /// </summary>
        internal static string SRB {
            get {
                return ResourceManager.GetString("SRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka.
        /// </summary>
        internal static string SRI {
            get {
                return ResourceManager.GetString("SRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Sudan.
        /// </summary>
        internal static string SSD {
            get {
                return ResourceManager.GetString("SSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao Tome and Principe.
        /// </summary>
        internal static string STP {
            get {
                return ResourceManager.GetString("STP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudan.
        /// </summary>
        internal static string SUD {
            get {
                return ResourceManager.GetString("SUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        internal static string SUI {
            get {
                return ResourceManager.GetString("SUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suriname.
        /// </summary>
        internal static string SUR {
            get {
                return ResourceManager.GetString("SUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakia.
        /// </summary>
        internal static string SVK {
            get {
                return ResourceManager.GetString("SVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        internal static string SWE {
            get {
                return ResourceManager.GetString("SWE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swaziland.
        /// </summary>
        internal static string SWZ {
            get {
                return ResourceManager.GetString("SWZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syria.
        /// </summary>
        internal static string SYR {
            get {
                return ResourceManager.GetString("SYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzania.
        /// </summary>
        internal static string TAN {
            get {
                return ResourceManager.GetString("TAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thailand.
        /// </summary>
        internal static string THA {
            get {
                return ResourceManager.GetString("THA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajikistan.
        /// </summary>
        internal static string TJK {
            get {
                return ResourceManager.GetString("TJK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmenistan.
        /// </summary>
        internal static string TKM {
            get {
                return ResourceManager.GetString("TKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timor-leste.
        /// </summary>
        internal static string TLS {
            get {
                return ResourceManager.GetString("TLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Togo.
        /// </summary>
        internal static string TOG {
            get {
                return ResourceManager.GetString("TOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Taipei.
        /// </summary>
        internal static string TPE {
            get {
                return ResourceManager.GetString("TPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinidad &amp; Tobago.
        /// </summary>
        internal static string TTO {
            get {
                return ResourceManager.GetString("TTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisia.
        /// </summary>
        internal static string TUN {
            get {
                return ResourceManager.GetString("TUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        internal static string TUR {
            get {
                return ResourceManager.GetString("TUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Arab Emirates.
        /// </summary>
        internal static string UAE {
            get {
                return ResourceManager.GetString("UAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uganda.
        /// </summary>
        internal static string UGA {
            get {
                return ResourceManager.GetString("UGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        internal static string UKR {
            get {
                return ResourceManager.GetString("UKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguay.
        /// </summary>
        internal static string URU {
            get {
                return ResourceManager.GetString("URU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States of America.
        /// </summary>
        internal static string USA {
            get {
                return ResourceManager.GetString("USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbekistan.
        /// </summary>
        internal static string UZB {
            get {
                return ResourceManager.GetString("UZB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela.
        /// </summary>
        internal static string VEN {
            get {
                return ResourceManager.GetString("VEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam.
        /// </summary>
        internal static string VIE {
            get {
                return ResourceManager.GetString("VIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wales.
        /// </summary>
        internal static string WLS {
            get {
                return ResourceManager.GetString("WLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemen.
        /// </summary>
        internal static string YEM {
            get {
                return ResourceManager.GetString("YEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zambia.
        /// </summary>
        internal static string ZAM {
            get {
                return ResourceManager.GetString("ZAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimbabwe.
        /// </summary>
        internal static string ZIM {
            get {
                return ResourceManager.GetString("ZIM", resourceCulture);
            }
        }
    }
}
