//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonzianiSwissGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PonzianiSwissGui.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bye.
        /// </summary>
        public static string Bye {
            get {
                return ResourceManager.GetString("Bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosstable.
        /// </summary>
        public static string Crosstable {
            get {
                return ResourceManager.GetString("Crosstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed - try again later!.
        /// </summary>
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update was successful!.
        /// </summary>
        public static string DownloadOk {
            get {
                return ResourceManager.GetString("DownloadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date less than Start Date.
        /// </summary>
        public static string EndDateLTStartDate {
            get {
                return ResourceManager.GetString("EndDateLTStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Tournament Report File.
        /// </summary>
        public static string ExportTRF {
            get {
                return ResourceManager.GetString("ExportTRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Files.
        /// </summary>
        public static string HTMLFiles {
            get {
                return ResourceManager.GetString("HTMLFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value - Please enter a float value!.
        /// </summary>
        public static string InvalidFloat {
            get {
                return ResourceManager.GetString("InvalidFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Tournament.
        /// </summary>
        public static string OpenTournamentFile {
            get {
                return ResourceManager.GetString("OpenTournamentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairings.
        /// </summary>
        public static string Pairings {
            get {
                return ResourceManager.GetString("Pairings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant List (By Name).
        /// </summary>
        public static string ParticipantListByName {
            get {
                return ResourceManager.GetString("ParticipantListByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant List (By Starting Rank).
        /// </summary>
        public static string ParticipantListByRank {
            get {
                return ResourceManager.GetString("ParticipantListByRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Files.
        /// </summary>
        public static string PDFFiles {
            get {
                return ResourceManager.GetString("PDFFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading and Updating Player Base....
        /// </summary>
        public static string PlayerListUpdate {
            get {
                return ResourceManager.GetString("PlayerListUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Tournament File.
        /// </summary>
        public static string SaveTournamentFile {
            get {
                return ResourceManager.GetString("SaveTournamentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament Files.
        /// </summary>
        public static string TournamentFiles {
            get {
                return ResourceManager.GetString("TournamentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TId.
        /// </summary>
        public static string TournamentIdShort {
            get {
                return ResourceManager.GetString("TournamentIdShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament Report File.
        /// </summary>
        public static string TournamentReportFile {
            get {
                return ResourceManager.GetString("TournamentReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
    }
}
